# Generated by Django 4.0.5 on 2022-06-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        ('earning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash', models.IntegerField(blank=True, null=True)),
                ('action', models.IntegerField(blank=True, choices=[(1, 'Credit'), (2, 'Debit')], null=True)),
                ('earning', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='earning.earning')),
                ('expense', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.expense')),
            ],
        ),
    ]
