# Generated by Django 4.0.5 on 2022-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expense', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, choices=[(1, 'Buy Goods'), (2, 'Travel'), (3, 'Food'), (4, 'Rent'), (5, 'Bill Payment'), (6, 'EMI Repayment'), (7, 'Movie'), (8, 'Family or Friends'), (9, 'Others')], null=True)),
                ('source_other', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
