# Generated by Django 4.0.5 on 2022-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earning', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, choices=[(1, 'Salary'), (2, 'Business'), (3, 'Others')], null=True)),
                ('source_other', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
